version: "3.8"

services:

  mysqldb_SB:
    image: mysql:8
    container_name: mysqldb_SB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop
    ports:
      - "3306:3306"
    volumes:
      - shop_db_data:/var/lib/shop
    networks:
      - shop_network

  shop_web_service:
    container_name: shop_web_service
    restart: always
    depends_on:
      - mysqldb_SB
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/shop
    networks:
      - shop_network
volumes:
  shop_db_data:
networks:
  shop_network: